### ISSUE TITLE
中控端軟體問題-VOC呈現時間不符

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#10]
VOC的測值在查詢時，跟PE提供的報表不符合?(我們的報表提前1個小時)
![image](https://user-images.githubusercontent.com/33660489/32785365-53dcfdb0-c98c-11e7-8854-db5e0e28a119.png)

**Comment by karateboy** [comment]
他檔案小時是1~24時, 所以11代表的是10點

**Comment by karateboy** [comment]
已改

**Comment by wenshoung** [comment]
我上去看報表，報表上呈現的時間還是提前一個小時，畫面如下

![image](https://user-images.githubusercontent.com/33660489/32870354-81a587d2-cab6-11e7-95cf-13ac9e493ea8.png)

**Comment by karateboy** [comment]
更新測站端軟體, 請重新檢查新的VOC資料
