### ISSUE TITLE
中控端軟體問題-無法匯出

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#12]
無法匯出PDF檔，錯誤畫面如下
![image](https://user-images.githubusercontent.com/33660489/32786118-13e5b3b2-c98e-11e7-82bc-8d2e5f4a34c4.png)

**Comment by wenshoung** [comment]
中控端已可匯出，但excel匯出的測項不對，如下圖所示


![image](https://user-images.githubusercontent.com/33660489/32873045-db55cdce-cac4-11e7-8caa-409e7206a323.png)

**Comment by karateboy** [comment]
Excel報表不在合約上, 先遮起來
