### ISSUE TITLE
中控端軟體問題-同期比較表問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#13]
”同期比較表”只有一個區間，如何篩選出同期的曲線圖?而且我查詢2016-10-14~2017-11-14，我點選資料卻顯示的是2016 11-14
![image](https://user-images.githubusercontent.com/33660489/32786504-19074fda-c98f-11e7-9120-2581e827122d.png)

**Comment by karateboy** [comment]
你選擇2017年, 就會列出2016, 2015年的同期資料比對
因為沒有歷史資料, 所以沒有

**Comment by wenshoung** [comment]
可是資料不應該顯示為2016的測值，且
下方應該顯示
       **2017  2016   2015**               才對

**Comment by karateboy** [comment]
查詢區限定是當年 2017-x-x 到2017-x-x
比對出2016/2015的資料
你的查詢區間跨年從2016到2017...所以會不正確
