### ISSUE TITLE
中控端軟體問題-測站資料內容錯誤無法更改

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#18]
維修保養內的設備管理，資料都是錯誤的，這個資料無法做更改?
![image](https://user-images.githubusercontent.com/33660489/32787194-ec60024a-c990-11e7-97c8-2022365e7375.png)

**Comment by karateboy** [comment]
這是寫死的....看是否要提供新的資料...要不然就這個網頁刪掉...

**Comment by wenshoung** [comment]
如果無法更改，建議先把此功能關閉
