### ISSUE TITLE
中控端軟體問題-VOC都查無資料

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#20]
測站端可以查到VOC資料，如下圖所示
![image](https://user-images.githubusercontent.com/33660489/32815709-57f40e84-c9f0-11e7-963f-e09f1582819a.png)

但是中控端都查不到，即時資訊、數據查詢、報表查詢都沒有

**Comment by karateboy** [comment]
上傳有問題...待修

**Comment by karateboy** [comment]
已經修正

**Comment by wenshoung** [comment]
報表查詢內，沒有voc資料?如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32872044-77700ed2-cabf-11e7-85e8-2ddb2f91efd7.png)
