### ISSUE TITLE
測站端軟體-網頁無法滑動問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#21]
在監測報表查詢時，我無法滑動網頁查看其他測項的數據，畫面如下：

![image](https://user-images.githubusercontent.com/33660489/32869920-79fd679a-cab4-11e7-80bb-81465eb8a38d.png)

**Comment by karateboy** [comment]
這個設計是...如果表單超過螢幕寬度, 最左邊會出現"+", 點開就會顯示.

**Comment by wenshoung** [comment]
可是....我點了左邊藍色的＋，還是無法往右移動


2017年11月16日 19:08，"Aragorn Huang" <notifications@github.com>寫道：

**Comment by karateboy** [comment]
點下"+"後, 資料就往下顯示了. 所以不會移動

**Comment by karateboy** [comment]
我改成卷軸了

**Comment by wenshoung** [comment]
畫面改成卷軸可以看到了，但是**"報表查詢"-->"監測報表"-->"月報"**  移過去卻看不到測項及測值，如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32924224-8641b160-cb76-11e7-8461-118346d981a4.png)

**Comment by wenshoung** [comment]
今天11/20的監測報表，VOC的00:00還是沒資料?

![image](https://user-images.githubusercontent.com/33660489/32997805-c282c370-cdcf-11e7-90b2-5623dc544200.png)

**Comment by karateboy** [comment]
@wenshoung 沒資料開新的issue....這個沒問題就關掉
