### ISSUE TITLE
測站端軟體問題-報表查詢(分鐘月報)

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#22]
監測月報內有"分鐘月報"，但查詢11月資料卻出現以下畫面，**建議將此報表移除**

![image](https://user-images.githubusercontent.com/33660489/32923869-cab7408c-cb74-11e7-9e32-2b072f6043b2.png)

**Comment by wenshoung** [comment]
無法查到分鐘報表

**Comment by karateboy** [comment]
不是說要拿掉了?

**Comment by wenshoung** [comment]
可是還在.........

**Comment by karateboy** [comment]
搞錯...中心端已經拿掉了

**Comment by wenshoung** [comment]
中心端(測站端)的"分鐘月報"還是沒有拿掉??


![image](https://user-images.githubusercontent.com/33660489/33049300-583ebae8-ce9a-11e7-8305-856b4c817ace.png)
