### ISSUE TITLE
測站軟體問題-匯出報表格式

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#23]
我嘗試去匯出日報、月報的PDF檔，但匯出的檔案是以下圖片，完全看不出測項及測值

![image](https://user-images.githubusercontent.com/33660489/32924075-e6914b94-cb75-11e7-80dd-87e0992c8afd.png)

**Comment by karateboy** [comment]
因為匯出報表, 有了VOC排版會太長...整個亂掉
把PDF拿掉吧

**Comment by wenshoung** [comment]
可是功能測試必須提交報告，如果沒有PDF或匯出方式，將無法提供日報，承辦也無法看出是否正常
