### ISSUE TITLE
測站端軟體問題-校正報表匯出錯誤

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#24]
數據查詢>校正資料查詢的PDF及EXCEL匯出都出現錯誤，如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32924549-1ffc4102-cb78-11e7-859b-8b195f1a452d.png)

**Comment by karateboy** [comment]
查一下合約  測站端有需要輸出報表嗎?
沒有就一樣把匯出功能都先關掉
