### ISSUE TITLE
測站軟體問題-VOC監測報表

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#26]
VOC的監測報表-->日報，00:00的測值怎麼都是"--"，如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32924720-fbcae09e-cb78-11e7-90f2-fc0aeb97dcb4.png)

**Comment by karateboy** [comment]
重新上傳資料已沒有這種問題

**Comment by wenshoung** [comment]
11/20的報表一樣的狀況
