### ISSUE TITLE
中控端軟體問題-監測日報表查不到資料

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#28]
剛查資料，發現11/16都還有測值，但是11/17都沒有測值，我也嘗試在測站端重新上傳資料，但還是一樣

![image](https://user-images.githubusercontent.com/33660489/32925125-413d5f4c-cb7b-11e7-9ccb-4f225ee2f66c.png)
上圖為11/16資料

![image](https://user-images.githubusercontent.com/33660489/32925171-7f06c994-cb7b-11e7-9939-a8f37c836a0c.png)
上圖為11/17空白的資料

**Comment by karateboy** [comment]
測站端軟體升級時, 忘了把上傳選項打開. 已經修正
