### ISSUE TITLE
測站軟體問題-報表無法匯出問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#3]
報表查詢時，**匯出PDF檔會出現錯誤訊息**，而**WORD檔無法匯出**
![image](https://user-images.githubusercontent.com/33660489/32784110-dc20a78e-c988-11e7-9827-cd5884c8bd47.png)
上圖為PDF匯出錯誤

![image](https://user-images.githubusercontent.com/33660489/32784141-f6906d02-c988-11e7-834a-a479a57d8129.png)
上圖為WORD匯出時空白

**Comment by karateboy** [comment]
晚點修...中控端有報表可以驗收先

**Comment by wenshoung** [comment]
測站端的word匯出有問題，會Word結果是excel，且測項不一樣，如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32872163-2c7c0952-cac0-11e7-80cb-efc67242f4f9.png)

**Comment by karateboy** [comment]
我們從頭到晚都是匯出Excel...不是Word.

**Comment by karateboy** [comment]
已經可以匯出PDF. 但VOC太多測項目, 其實不實用.
至於Excel報表, 合約沒說要提供這. 所以先遮掉
