### ISSUE TITLE
中心端軟體問題-VOC月份時報表有問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#33]
報表查詢-->月份時報表，VOC資料在11/21 09:00後就沒有測值了，空品測站的都有，我也嘗試在測站端重新上傳資料，仍然沒有測值

以下為VOC 己烷的報表
![image](https://user-images.githubusercontent.com/33660489/33227684-84c132c0-d1e3-11e7-8f92-9f0fa09f0e98.png)

**Comment by karateboy** [comment]
已先回補
