### ISSUE TITLE
中心端軟體問題-VOC無監測報表?

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#34]
之前監測報表內都有VOC的資料，怎麼現在沒有了?
我查歷史資料，也是在11/21 09:00就沒有資料，可以查看看嗎??

**Comment by karateboy** [comment]
歷史資料有....VOC的監測報表, 等乙琦和承辦談好再說
VOC報表混入一般測項報表真的太亂了

**Comment by karateboy** [comment]
[和這個重複](https://github.com/karateboy/EPA2/issues/15)
