### ISSUE TITLE
測站端及中控端-VOC無資料

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#35]
11/30 23:00及12/1 00:00無資料
12/2 15::00之後都沒有資料
但我看VOC電腦內都有資料~請協助檢查原因

![image](https://user-images.githubusercontent.com/33660489/33521710-7d3bbe1c-d814-11e7-9a22-d073dcad1ff4.png)

**Comment by karateboy** [comment]
已經修正, 請複查

**Comment by wenshoung** [comment]
11/30 23:00
12/1   00:00
這2筆還是沒有資料顯示???
