### ISSUE TITLE
中控端軟體問題-合理性稽核怎麼沒動作?

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#36]
我啟用了合理性判斷，但NOx<NO2卻沒有標示"自動檢核"的框框

![image](https://user-images.githubusercontent.com/33660489/33583783-04727b0e-d997-11e7-8ff0-d63b4801ab36.png)

![image](https://user-images.githubusercontent.com/33660489/33583792-1283812a-d997-11e7-8f08-8ec83c3ed372.png)

**Comment by karateboy** [comment]
你幾時開的? 啟用後, 只會套用的新的資料上
另外你標示的那個資料, 看上去沒問題呀
是有違反哪一條?

**Comment by wenshoung** [comment]
NOx    NO2     NO
 2.0       2.0      -0.1
 5.9       6.0      -0.1

NOx < NO2

**Comment by karateboy** [comment]
合理呀, 你看的數字是四捨五入
5.9 >= 6.0 + (-0.1)
