### ISSUE TITLE
測站端軟體問題-可用率問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#38]
測站端已標示無效資料，為什麼可用率還是100%
中控端標示正常，但還是顯示無效??

![image](https://user-images.githubusercontent.com/33660489/33748040-3f2acbea-dc01-11e7-9e0c-4acf1e3b8ad5.png)

可用率跟沒有標示的一樣，都沒變
![image](https://user-images.githubusercontent.com/33660489/33748047-4ed63c6e-dc01-11e7-84e0-2a5134caacc9.png)

11/26號的資料，一樣是有效率100%
![image](https://user-images.githubusercontent.com/33660489/33748063-6cbd189c-dc01-11e7-918d-7b66adb5f785.png)

**Comment by karateboy** [comment]
這是資料蒐集器的bug, 以前一直沒人驗證. 
請優先驗證中控端報表

**Comment by wenshoung** [comment]
中控端部分，我試著將他改回正常測值，但還是標示無效.....

**Comment by karateboy** [comment]
中控端已更新修正.

**Comment by wenshoung** [comment]
中控端部分，我嘗試將PM2.5 12/18 06:00標示無效測值，但無法標示

![image](https://user-images.githubusercontent.com/33660489/34099062-5b9f61b2-e419-11e7-9e2e-9054d7050d0b.png)

沒有沒有出現標示的狀況
![image](https://user-images.githubusercontent.com/33660489/34099066-64bd07ea-e419-11e7-9486-29ebf0864de7.png)

**Comment by karateboy** [comment]
已經修正...
