### ISSUE TITLE
中控端問題-監測月報無資料

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#41]
原本原本12/12 08:00之後都沒有測值，
於15:44重新上傳資料後正常，但屬不正常現象，請協助檢查是否會突然停止上傳?

![image](https://user-images.githubusercontent.com/33660489/33872849-87945176-df53-11e7-8ce1-8a11d2a34795.png)

**Comment by karateboy** [comment]
這是維修造成的!
請到歷史趨勢圖/歷史資料選擇顯示全部資料就知道問題原因
