### ISSUE TITLE
測站端軟體問題-監測月報問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#42]
監測月報內15:00，AQM部分怎麼沒有資料?(風速風向溫度溼度都沒有)
我於13:51執行維修模式

![image](https://user-images.githubusercontent.com/33660489/33872887-b6dc1658-df53-11e7-9b5a-d7635cfd672a.png)

**Comment by karateboy** [comment]
這是正確的...因為維修時, 有效率低於75%就小時值無效. 
該小時值是"正常值"的平均, 因為那小時沒有正常值, 所以就是空的

詳請請問YS, 我也覺得這是亂七八糟的規定
