### ISSUE TITLE
中控端軟體問題-提供合約規範及建議

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#6]
提供中控端軟體規範如下
資料監測蒐集系統軟體部分(局內接收端)：
(1). 具收集、儲存、處理、數據呈現與校正值呈現功能。 
(2). 資料軟體儲存資料庫需搭配 Oracle或SQL Data Base或同級品。  
(3). 可顯示趨勢圖及日報表、月報表等。  
(4). 可每小時將監測小時值自動傳輸至環保署空氣品質監測網站，監測規範須符合環保署需求。

建議數據都不要跟環保署做比對
![image](https://user-images.githubusercontent.com/33660489/32786051-eb19d44a-c98d-11e7-9279-3410bb81e964.png)

**Comment by karateboy** [comment]
fixed.

**Comment by wenshoung** [comment]
數據查詢中還是有跟環保局做比較，建議功能關閉，如下圖所示

![image](https://user-images.githubusercontent.com/33660489/32871940-f141a2da-cabe-11e7-8974-b4349805a3ec.png)

**Comment by karateboy** [comment]
已移除
