### ISSUE TITLE
中控端軟體問題-即時畫面問題

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#8]
即時畫面中只有測站的位置，是否要增加監測項目或將此畫面刪除，目前看不出這個畫面的用意

**Comment by karateboy** [comment]
使用者可以客製化首頁...到"系統管理">"使用者管理">"即時畫面控制項"

**Comment by wenshoung** [comment]
我在中控端的"系統管理">"使用者管理"中沒看到**"即時畫面控制項"**

![image](https://user-images.githubusercontent.com/33660489/32872316-0bad55ea-cac1-11e7-86a4-858fdea61f77.png)

**Comment by karateboy** [comment]
關注測站下面, 就是即時畫面控制項.
點選後儲存回到即時畫面
