### ISSUE TITLE
中控端軟體問題-網頁無法滑動及建議

### ISSUE THREAD

**Issue by wenshoung** [karateboy/EPA2#9]
即時數據中的**網頁無法滑動**，無法看到VOC全部的測項及測值，**建議VOC不需要在即時資訊中查詢**
![image](https://user-images.githubusercontent.com/33660489/32785265-1b32f726-c98c-11e7-81f3-620c47b411ea.png)

**Comment by karateboy** [comment]
已移除VOC測項, 另外當螢幕無法顯示, 會有一個綠色+, 點後會打開
